Title
Sergo-developer/DungeonCrawler pull request #1
Opened 2024-02-25 09:26 UTC by Sergo-developer

2024-02-25 09:27 UTC, ixpl0 commented on src/components/EnemyScreen.vue
> +.enemy-level {
добавь пустые строки между блоками, чтобы не слипалось

2024-02-26 21:44 UTC, akashcheev requested changes

2024-02-26 21:44 UTC, akashcheev commented on src/App.vue
>  .game-wrapper {
добавляй пустые строки между блоками. Мб для этого в будущем поставим StyleLint

2024-02-26 21:44 UTC, akashcheev commented on src/components/EnemyScreen.vue
> +const enemyMaxHealth = ref(currentRoom.value.enemy.health);
надо исправлять TS ошибки. Предлагаю так:

```
const enemyMaxHealth = ref(0);

watch(
  currentRoom as ComputedRef<EnemyRoom>,
  (value) => {
    enemyMaxHealth.value = value.enemy.health;
  },
  { immediate: true },
);
```

ну и заодно узнай, что такое immediate: true

2024-02-26 21:44 UTC, akashcheev commented on src/components/EnemyScreen.vue
> +.enemy-name {
пробегись, добавь пустых строк между блоками

2024-02-26 21:44 UTC, akashcheev commented on src/components/MainScreen.vue
> +const { currentRoom, movePosition, player } = inject('state') as State;
player не используется, удалить

2024-02-26 21:44 UTC, akashcheev commented on src/components/MainScreen.vue
> +  () => currentRoom.value.type.name !== 'enemy' || currentRoom.value.isDefeated,
заткни TS
(currentRoom.value as EnemyRoom).isDefeated

2024-02-26 21:44 UTC, akashcheev commented on src/hooks/useFight.ts
> +  const totalPlayerDamage = ref(
судя по всему, тут нужен computed, тк это выглядит статично и как баг

2024-02-26 21:44 UTC, akashcheev commented on src/hooks/useFight.ts
> +    isFight.value = true;
вот это лучше перенести после if, так как там оно мгновенно выключается никак не влияя ни на что

2024-02-26 21:44 UTC, akashcheev commented on src/hooks/useFight.ts
> +    await wait(1000);
вот прям перед await вставить
isFight.value = true;

2024-02-26 21:44 UTC, akashcheev commented on src/hooks/useFight.ts
> +      isFight.value = false;
ну и это удалить соответственно

2024-02-26 21:44 UTC, akashcheev commented on src/stores/roomsDatabase.ts
> +export const types = [
я б добавил типы, для понятности
типа export const types: Type[] = [

2024-02-26 21:44 UTC, akashcheev commented on src/stores/roomsDatabase.ts
> +export const roomsDatabase = [
аналогично :Enemy[]

2024-02-26 21:44 UTC, akashcheev commented on src/types/map.ts
а этот файл имхо уже пора разбивать на птематические подфайлы

2024-02-26 21:44 UTC, akashcheev commented on src/utils/dungeon-map.ts
> +        enemy: structuredClone(roomsDatabase[randomRange(0, roomsDatabase.length - 1)]),
вот тут не оч понятно. Ты врага записываешь в комнату, даже если комната никак с врагом не связана?

2024-02-27 14:03 UTC, merged